
import { Book, Category } from './types';

export const BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    price: 18.99,
    rating: 4.8,
    category: Category.FICTION,
    coverImage: 'https://picsum.photos/seed/library/400/600',
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    isBestseller: true,
  },
  {
    id: '2',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    price: 24.50,
    rating: 4.9,
    category: Category.SCI_FI,
    coverImage: 'https://picsum.photos/seed/space/400/600',
    description: 'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish.',
  },
  {
    id: '3',
    title: 'Educated',
    author: 'Tara Westover',
    price: 14.20,
    rating: 4.7,
    category: Category.BIOGRAPHY,
    coverImage: 'https://picsum.photos/seed/educated/400/600',
    description: 'An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    isBestseller: true,
  },
  {
    id: '4',
    title: 'Atomic Habits',
    author: 'James Clear',
    price: 19.99,
    rating: 5.0,
    category: Category.NON_FICTION,
    coverImage: 'https://picsum.photos/seed/habits/400/600',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving—every day.',
    isBestseller: true,
  },
  {
    id: '5',
    title: 'Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 12.00,
    rating: 4.5,
    category: Category.CLASSICS,
    coverImage: 'https://picsum.photos/seed/gatsby/400/600',
    description: 'A classic novel set in the Roaring Twenties that follows a cast of characters living in the fictional towns of West Egg and East Egg on prosperous Long Island.',
  },
  {
    id: '6',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 16.75,
    rating: 4.6,
    category: Category.MYSTERY,
    coverImage: 'https://picsum.photos/seed/patient/400/600',
    description: 'Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house in London.',
  },
  {
    id: '7',
    title: 'Dune',
    author: 'Frank Herbert',
    price: 22.00,
    rating: 4.7,
    category: Category.SCI_FI,
    coverImage: 'https://picsum.photos/seed/dune/400/600',
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.',
  },
  {
    id: '8',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    price: 21.50,
    rating: 4.8,
    category: Category.NON_FICTION,
    coverImage: 'https://picsum.photos/seed/sapiens/400/600',
    description: 'From a renowned historian comes a groundbreaking narrative of humanity’s creation and evolution.',
  },
];
